linters-settings:
  gocyclo:
    min-complexity: 24
  cyclop:
    max-complexity: 24
  forbidigo:
    forbid:
      - .*\.fatal,*
      - fmt.Print.*
  gci:
    skip-generated: true
  gofmt:
    simplify: true
  lll:
    line-length: 160

linters:
  disable:
    - depguard
    - exhaustruct
    - ireturn
    - tagalign
    - tenv
    - varnamelen

run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number

issues:
  exclude-rules:
    - path: tests/.*
      linters:
        - funlen
