services:
  postgres:
    container_name: postgres_wallets
    image: postgres:latest
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: wallets_db
    volumes:
      - postgres-data:/var/lib/postgres
    ports:
      - "5432:5432"
    
volumes:
  postgres-data: