name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - uses: golangci/golangci-lint-action@v4
        with:
          version: v1.64.5
          args: --timeout=5m
  
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: wallets_db
          POSTGRES_USER: ${{secrets.DB_USERNAME}}
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
    env:
      DATABASE_URL: postgresql://${{secrets.DB_USERNAME}}:${{secrets.DB_PASSWORD}}@localhost:5432/wallets_db
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - uses: actions/checkout@v4
      - run: until pg_isready -h localhost -p 5432; do echo "Waiting for postgres ..."; sleep 1; done
      - run: go test -race ./...

  build:
    strategy:
      matrix:
        go-version: [ ^1.24.1 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: 
          go-version: ${{ matrix.go-version }}
      - run: go build ./cmd/wallets-service/main.go

  