name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
      - uses: golangci/golangci-lint-action@v4
        with:
          version: v1.64.5
          args: --timeout=5m

  build:
    strategy:
      matrix:
        go-version: [ ^1.24.0 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: 
          go-version: ${{ matrix.go-version }}
      - run: go build ./cmd/wallets-service/main.go

  #TODO tests